version: '3'

services:
  app:
    image: ghcr.io/bacnh85/docker-gitolite-cgit:latest
    container_name: gitolite-cgit
    env_file: config.env
    volumes:
      - git:/var/lib/git/
    ports:
      - "22:22"
      - "80:80"
      - "9418:9418"
    tty: true
volumes: 
  git:
